### ISSUE TITLE
Define standard language for logging.

### ISSUE THREAD

**Issue by dilsonnn** [tnsc4502/mnwvs077#2]
Hi.

Since people from around the world can collaborate with the project. I would like to propose that the source adhere to this standard:

- All log messages should be defined in english without rely on StringPool.

- Internal administration feedback messages such as the ones sent to Game Masters upon feature configuration should be defined in english without using the StringPool.

- All messages sent to the client should be defined using the StringPool.

- Scripts of all kind should support keys for internationalization. For example, the Script API must be able to translate a label key provided.  Each script  should have its own internationalization file, for example:
`Quest/2000.lua Quest/2000_en.locale Quest/2000_tw.locale.`

Nevertheless, I want to mention that the source code is looking beautiful, really good job!

**Comment by tnsc4502** [comment]
Hi, thanks for your reply, again.
I appreciate for the suggestions you provided, but the first one actually confused me for a long while.
Because I saw many people struggle on translating all console messages to their own native language in different sources, for example, the original KMS source released by koreans, and many TWMS sources are so.
Thus currently I'm considering to leave a space for developers from different countries to customize the source in their own preferred language.

**Comment by undefined-sin** [comment]
Every application should use english for comments / logs. The source code is written in english, so it make it more confortable and available for everyone. 

Also, Imagine that you will put this server and have to hire someone to monitor the application in production. If you use korean, the person managing it will have to know korean to grep the logs. 

Best,
